# Generated by Django 3.0.4 on 2020-04-26 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of the category')),
                ('img', models.TextField(verbose_name='path to the image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_photo', models.TextField(verbose_name='Review Photo')),
                ('review_name', models.CharField(max_length=200, verbose_name='Review Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('video_path', models.TextField(verbose_name='Video Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Newses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.TextField(verbose_name='News Photo')),
                ('news_name', models.CharField(max_length=200, verbose_name='News Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.TextField(verbose_name='News Photo')),
                ('news_name', models.CharField(max_length=200, verbose_name='News Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='User Name')),
                ('user_email', models.CharField(max_length=200, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='GameBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('short_name', models.CharField(max_length=200, verbose_name='short name')),
                ('price', models.FloatField(verbose_name='price')),
                ('genre', models.CharField(max_length=200, verbose_name='genre')),
                ('developer', models.CharField(max_length=200, verbose_name='developer')),
                ('publisher', models.CharField(max_length=200, verbose_name='publisher')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('description', models.TextField(verbose_name='description')),
                ('img_path', models.TextField(verbose_name='image path')),
                ('video_path', models.TextField(verbose_name='video_path')),
                ('os_min', models.TextField(default='Min OS', verbose_name='Min OS')),
                ('processor_min', models.TextField(default='Min processor', verbose_name='Min processor')),
                ('memory_min', models.TextField(default='Min memory', verbose_name='Min memory')),
                ('graphics_min', models.TextField(default='Min graphics', verbose_name='Min graphics')),
                ('space_min', models.TextField(default='Min Space', verbose_name='Min space')),
                ('os_opt', models.TextField(default='Optimal OS', verbose_name='Optimal OS')),
                ('processor_opt', models.TextField(default='Optimal processor', verbose_name='Optimal processor')),
                ('memory_opt', models.TextField(default='Optimal memory', verbose_name='Optimal memory')),
                ('graphics_opt', models.TextField(default='Optimal graphics', verbose_name='Optimal graphics')),
                ('space_opt', models.TextField(default='Optimal space', verbose_name='Optimal space')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='mainApp.Category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='CartsAndGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Cart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Game')),
            ],
            options={
                'verbose_name': 'CartsAndGames',
                'verbose_name_plural': 'CartsAndGames',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('card_number', models.IntegerField(verbose_name='Card Number')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('money_amount', models.FloatField(max_length=20, verbose_name='Money')),
                ('security_code', models.IntegerField(verbose_name='Security Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='BoxesAndGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.GameBox')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Game')),
            ],
            options={
                'verbose_name': 'BoxesAndGames',
                'verbose_name_plural': 'BoxesAndGames',
            },
        ),
    ]
